
import { Player, Role, RankingEntry } from './types';

export const INITIAL_BUDGET = 100.0;

export const MOCK_RANKING: RankingEntry[] = [
  { rank: 1, userName: 'BAIANO', teamName: 'ILHA DAS LENDAS', points: 1342.5, trend: 'stable' },
  { rank: 2, userName: 'TitaN BR', teamName: 'MAQUINA DE PONTOS', points: 1250.2, trend: 'up' },
];

export const CHAMPION_ROLES_MAP: Record<string, Role[]> = {
  "Aatrox": [Role.TOP],
  "Ahri": [Role.MID],
  "Akali": [Role.MID, Role.TOP],
  "Akshan": [Role.MID, Role.TOP],
  "Alistar": [Role.SUP],
  "Ambessa": [Role.TOP, Role.JNG],
  "Amumu": [Role.JNG, Role.SUP],
  "Anivia": [Role.MID],
  "Annie": [Role.MID, Role.SUP],
  "Aphelios": [Role.ADC],
  "Ashe": [Role.ADC, Role.SUP],
  "AurelionSol": [Role.MID],
  "Aurora": [Role.MID, Role.TOP],
  "Azir": [Role.MID],
  "Bard": [Role.SUP],
  "Belveth": [Role.JNG],
  "Blitzcrank": [Role.SUP],
  "Brand": [Role.SUP, Role.MID],
  "Braum": [Role.SUP],
  "Briar": [Role.JNG],
  "Caitlyn": [Role.ADC],
  "Camille": [Role.TOP],
  "Cassiopeia": [Role.MID],
  "Chogath": [Role.TOP, Role.MID],
  "Corki": [Role.MID, Role.ADC],
  "Darius": [Role.TOP],
  "Diana": [Role.JNG, Role.MID],
  "DrMundo": [Role.TOP, Role.JNG],
  "Draven": [Role.ADC],
  "Ekko": [Role.JNG, Role.MID],
  "Elise": [Role.JNG],
  "Evelynn": [Role.JNG],
  "Ezreal": [Role.ADC],
  "Fiddlesticks": [Role.JNG],
  "Fiora": [Role.TOP],
  "Fizz": [Role.MID],
  "Galio": [Role.MID, Role.SUP],
  "Gangplank": [Role.TOP],
  "Garen": [Role.TOP],
  "Gnar": [Role.TOP],
  "Gragas": [Role.JNG, Role.TOP],
  "Graves": [Role.JNG],
  "Gwen": [Role.TOP, Role.JNG],
  "Hecarim": [Role.JNG],
  "Heimerdinger": [Role.SUP, Role.MID],
  "Hwei": [Role.MID, Role.SUP],
  "Illaoi": [Role.TOP],
  "Irelia": [Role.TOP, Role.MID],
  "Ivern": [Role.JNG],
  "Janna": [Role.SUP],
  "JarvanIV": [Role.JNG],
  "Jax": [Role.TOP, Role.JNG],
  "Jayce": [Role.TOP, Role.MID],
  "Jhin": [Role.ADC],
  "Jinx": [Role.ADC],
  "Kaisa": [Role.ADC],
  "Kalista": [Role.ADC],
  "Karma": [Role.SUP, Role.MID],
  "Karthus": [Role.JNG, Role.ADC],
  "Kassadin": [Role.MID],
  "Katarina": [Role.MID],
  "Kayle": [Role.TOP],
  "Kayn": [Role.JNG],
  "Kennen": [Role.TOP],
  "Khazix": [Role.JNG],
  "Kindred": [Role.JNG],
  "Kled": [Role.TOP],
  "KogMaw": [Role.ADC],
  "KSante": [Role.TOP],
  "Leblanc": [Role.MID],
  "LeeSin": [Role.JNG],
  "Leona": [Role.SUP],
  "Lillia": [Role.JNG],
  "Lissandra": [Role.MID],
  "Lucian": [Role.ADC],
  "Lulu": [Role.SUP],
  "Lux": [Role.SUP, Role.MID],
  "Malphite": [Role.TOP, Role.SUP],
  "Malzahar": [Role.MID],
  "Maokai": [Role.SUP, Role.JNG, Role.TOP],
  "MasterYi": [Role.JNG],
  "Milio": [Role.SUP],
  "MissFortune": [Role.ADC],
  "MonkeyKing": [Role.JNG, Role.TOP],
  "Mordekaiser": [Role.TOP],
  "Morgana": [Role.SUP],
  "Naafiri": [Role.MID],
  "Nami": [Role.SUP],
  "Nasus": [Role.TOP],
  "Nautilus": [Role.SUP],
  "Neeko": [Role.SUP, Role.MID],
  "Nidalee": [Role.JNG],
  "Nilah": [Role.ADC],
  "Nocturne": [Role.JNG],
  "Nunu": [Role.JNG],
  "Olaf": [Role.JNG, Role.TOP],
  "Orianna": [Role.MID],
  "Ornn": [Role.TOP],
  "Pantheon": [Role.SUP, Role.TOP, Role.MID],
  "Poppy": [Role.JNG, Role.SUP, Role.TOP],
  "Pyke": [Role.SUP],
  "Qiyana": [Role.MID, Role.JNG],
  "Quinn": [Role.TOP],
  "Rakan": [Role.SUP],
  "Rammus": [Role.JNG],
  "RekSai": [Role.JNG],
  "Rell": [Role.SUP],
  "Renata": [Role.SUP],
  "Renekton": [Role.TOP],
  "Rengar": [Role.JNG, Role.TOP],
  "Riven": [Role.TOP],
  "Rumble": [Role.TOP, Role.MID],
  "Ryze": [Role.MID, Role.TOP],
  "Samira": [Role.ADC],
  "Sejuani": [Role.JNG],
  "Senna": [Role.SUP, Role.ADC],
  "Seraphine": [Role.SUP, Role.ADC, Role.MID],
  "Sett": [Role.TOP, Role.SUP],
  "Shaco": [Role.JNG, Role.SUP],
  "Shen": [Role.TOP, Role.SUP],
  "Shyvana": [Role.JNG],
  "Singed": [Role.TOP],
  "Sion": [Role.TOP],
  "Sivir": [Role.ADC],
  "Skarner": [Role.JNG],
  "Smolder": [Role.ADC],
  "Sona": [Role.SUP],
  "Soraka": [Role.SUP],
  "Swain": [Role.SUP, Role.MID],
  "Sylas": [Role.MID, Role.JNG],
  "Syndra": [Role.MID],
  "TahmKench": [Role.SUP, Role.TOP],
  "Taliyah": [Role.JNG, Role.MID],
  "Talon": [Role.MID, Role.JNG],
  "Taric": [Role.SUP],
  "Teemo": [Role.TOP],
  "Thresh": [Role.SUP],
  "Tristana": [Role.ADC, Role.MID],
  "Trundle": [Role.JNG, Role.TOP],
  "Tryndamere": [Role.TOP],
  "TwistedFate": [Role.MID],
  "Twitch": [Role.ADC, Role.SUP],
  "Udyr": [Role.JNG],
  "Urgot": [Role.TOP],
  "Varus": [Role.ADC, Role.MID],
  "Vayne": [Role.ADC, Role.TOP],
  "Veigar": [Role.MID, Role.SUP],
  "Velkoz": [Role.SUP, Role.MID],
  "Vex": [Role.MID],
  "Vi": [Role.JNG],
  "Viego": [Role.JNG],
  "Viktor": [Role.MID],
  "Vladimir": [Role.MID, Role.TOP],
  "Volibear": [Role.JNG, Role.TOP],
  "Warwick": [Role.JNG, Role.TOP],
  "Xayah": [Role.ADC],
  "Xerath": [Role.SUP, Role.MID],
  "XinZhao": [Role.JNG],
  "Yasuo": [Role.MID, Role.TOP],
  "Yone": [Role.MID, Role.TOP],
  "Yorick": [Role.TOP],
  "Yuumi": [Role.SUP],
  "Zac": [Role.JNG],
  "Zed": [Role.MID],
  "Zeri": [Role.ADC],
  "Ziggs": [Role.ADC, Role.MID],
  "Zilean": [Role.SUP, Role.MID],
  "Zoe": [Role.MID],
  "Zyra": [Role.SUP],
  "Zaahen": [Role.JNG, Role.TOP]
};

export const CHAMPIONS_LIST = Object.keys(CHAMPION_ROLES_MAP).sort();
export const INITIAL_BUDGET_DISPLAY = 100.0;

// O MOCK_PLAYERS será substituído pelo fetch real do Supabase no App.tsx
export const MOCK_PLAYERS: Player[] = [];
